# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pvcontrol.ui'
#
# Created: Tue Mar 24 23:33:19 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pvControl(object):
    def setupUi(self, pvControl):
        pvControl.setObjectName("pvControl")
        pvControl.resize(380, 480)
        pvControl.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.mppt_chnl3_on_off = QtWidgets.QPushButton(pvControl)
        self.mppt_chnl3_on_off.setGeometry(QtCore.QRect(220, 332, 81, 51))
        self.mppt_chnl3_on_off.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.mppt_chnl3_on_off.setObjectName("mppt_chnl3_on_off")
        self.mppt_chnl2_operating_state = QtWidgets.QLabel(pvControl)
        self.mppt_chnl2_operating_state.setGeometry(QtCore.QRect(190, 140, 131, 21))
        self.mppt_chnl2_operating_state.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.mppt_chnl2_operating_state.setAlignment(QtCore.Qt.AlignCenter)
        self.mppt_chnl2_operating_state.setObjectName("mppt_chnl2_operating_state")
        self.mppt_chnl3_on_off_indicator = QtWidgets.QLabel(pvControl)
        self.mppt_chnl3_on_off_indicator.setGeometry(QtCore.QRect(186, 202, 131, 26))
        self.mppt_chnl3_on_off_indicator.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"")
        self.mppt_chnl3_on_off_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.mppt_chnl3_on_off_indicator.setObjectName("mppt_chnl3_on_off_indicator")
        self.label_mppt_chnl2 = QtWidgets.QLabel(pvControl)
        self.label_mppt_chnl2.setGeometry(QtCore.QRect(50, 62, 101, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_mppt_chnl2.setFont(font)
        self.label_mppt_chnl2.setStyleSheet("color: rgb(0, 0, 255);\n"
"")
        self.label_mppt_chnl2.setObjectName("label_mppt_chnl2")
        self.mppt_chnl2_on_off = QtWidgets.QPushButton(pvControl)
        self.mppt_chnl2_on_off.setGeometry(QtCore.QRect(80, 332, 81, 51))
        self.mppt_chnl2_on_off.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.mppt_chnl2_on_off.setObjectName("mppt_chnl2_on_off")
        self.mppt_chnl2_on_off_indicator = QtWidgets.QLabel(pvControl)
        self.mppt_chnl2_on_off_indicator.setGeometry(QtCore.QRect(190, 100, 131, 21))
        self.mppt_chnl2_on_off_indicator.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);")
        self.mppt_chnl2_on_off_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.mppt_chnl2_on_off_indicator.setObjectName("mppt_chnl2_on_off_indicator")
        self.mppt_chnl3_operating_state = QtWidgets.QLabel(pvControl)
        self.mppt_chnl3_operating_state.setGeometry(QtCore.QRect(190, 248, 131, 21))
        self.mppt_chnl3_operating_state.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.mppt_chnl3_operating_state.setAlignment(QtCore.Qt.AlignCenter)
        self.mppt_chnl3_operating_state.setObjectName("mppt_chnl3_operating_state")
        self.label_operating_state = QtWidgets.QLabel(pvControl)
        self.label_operating_state.setGeometry(QtCore.QRect(50, 143, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_operating_state.setFont(font)
        self.label_operating_state.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_operating_state.setObjectName("label_operating_state")
        self.label_status_2 = QtWidgets.QLabel(pvControl)
        self.label_status_2.setGeometry(QtCore.QRect(50, 101, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_status_2.setFont(font)
        self.label_status_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_status_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_status_2.setObjectName("label_status_2")
        self.label_mppt_chnl3 = QtWidgets.QLabel(pvControl)
        self.label_mppt_chnl3.setGeometry(QtCore.QRect(50, 172, 101, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_mppt_chnl3.setFont(font)
        self.label_mppt_chnl3.setStyleSheet("color: rgb(0, 0, 255);\n"
"")
        self.label_mppt_chnl3.setObjectName("label_mppt_chnl3")
        self.label_control = QtWidgets.QLabel(pvControl)
        self.label_control.setGeometry(QtCore.QRect(50, 282, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_control.setFont(font)
        self.label_control.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_control.setObjectName("label_control")
        self.label_operating_state_2 = QtWidgets.QLabel(pvControl)
        self.label_operating_state_2.setGeometry(QtCore.QRect(50, 248, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_operating_state_2.setFont(font)
        self.label_operating_state_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_operating_state_2.setObjectName("label_operating_state_2")
        self.label_status_3 = QtWidgets.QLabel(pvControl)
        self.label_status_3.setGeometry(QtCore.QRect(50, 206, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_status_3.setFont(font)
        self.label_status_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_status_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_status_3.setObjectName("label_status_3")
        self.label_title = QtWidgets.QLabel(pvControl)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_title.setStyleSheet("color: rgb(255, 255, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")

        self.retranslateUi(pvControl)
        QtCore.QMetaObject.connectSlotsByName(pvControl)

    def retranslateUi(self, pvControl):
        _translate = QtCore.QCoreApplication.translate
        pvControl.setWindowTitle(_translate("pvControl", "pvControl"))
        self.mppt_chnl3_on_off.setText(_translate("pvControl", "On/Off \n"
"Chnl 3"))
        self.mppt_chnl2_operating_state.setText(_translate("pvControl", "-"))
        self.mppt_chnl3_on_off_indicator.setText(_translate("pvControl", "-"))
        self.label_mppt_chnl2.setText(_translate("pvControl", "Channel 2"))
        self.mppt_chnl2_on_off.setText(_translate("pvControl", "On/Off \n"
"Chnl 2"))
        self.mppt_chnl2_on_off_indicator.setText(_translate("pvControl", "-"))
        self.mppt_chnl3_operating_state.setText(_translate("pvControl", "-"))
        self.label_operating_state.setText(_translate("pvControl", "Operating State:"))
        self.label_status_2.setText(_translate("pvControl", "Status:"))
        self.label_mppt_chnl3.setText(_translate("pvControl", "Channel 3"))
        self.label_control.setText(_translate("pvControl", "Control"))
        self.label_operating_state_2.setText(_translate("pvControl", "Operating State:"))
        self.label_status_3.setText(_translate("pvControl", "Status:"))
        self.label_title.setText(_translate("pvControl", "PHOTOVOLTAIC CONTROL"))

