######################################################################
# Automatically generated by qmake (3.1) Thu Sep 14 12:26:08 2017
######################################################################

TEMPLATE = app
TARGET = build-battery1Control-Desktop-Debug
INCLUDEPATH += .

# Input
HEADERS += ui_battery1control.h
